In [1]:
import pandas as pd
import numpy as np

In [2]:
np.random.seed(357823)

In [ ]:
dataframe = pd.read_csv('movies.csv', delimiter = ';')
#Esto quita las filas con valores null
dataframe.dropna(inplace=True)
dataframe.head()

,title,genres,poster_path
0,Meg 2: The Trench,Action-Science Fiction-Horror,/4m1Au3YkjqsxF8iwQy0fPYSxE0h.jpg
1,The Pope's Exorcist,Horror-Mystery-Thriller,/9JBEPLTPSm0d1mbEcLxULjJq9Eh.jpg
2,Deadpool & Wolverine,Action-Comedy-Science Fiction,/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg
3,Transformers: Rise of the Beasts,Action-Adventure-Science Fiction,/gPbM0MK8CP8A174rmUwGsADNYKD.jpg
4,Dune: Part Two,Science Fiction-Adventure,/czembW0Rk1Ke7lCJGahbOhdCuhV.jpg

In [ ]:
#Obtener todos los géneros de las películas 
dataframe["genres"].str.split("-").explode().unique()

array(['Action', 'Science Fiction', 'Horror', 'Mystery', 'Thriller',
       'Comedy', 'Adventure', 'Drama', 'Animation', 'Family', 'Fantasy',
       'History', 'War', 'Crime', 'Romance', 'Documentary', 'Music',
       'TV Movie', 'Western'], dtype=object)

In [14]:
len(dataframe)

415966

In [15]:
#Modificar el dataframe de forma que tenga columnas binarias por cada género 
# y eliminando la columna de géneros (ya no es relevante)

dataframe = dataframe.drop(columns="genres").join(dataframe["genres"].str.get_dummies(sep="-"))
dataframe.head()

,title,poster_path,Action,Adventure,Animation,Comedy,Crime,Documentary,Drama,Family,...,History,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western
0,Meg 2: The Trench,/4m1Au3YkjqsxF8iwQy0fPYSxE0h.jpg,1,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0
1,The Pope's Exorcist,/9JBEPLTPSm0d1mbEcLxULjJq9Eh.jpg,0,0,0,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
2,Deadpool & Wolverine,/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg,1,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,Transformers: Rise of the Beasts,/gPbM0MK8CP8A174rmUwGsADNYKD.jpg,1,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,Dune: Part Two,/czembW0Rk1Ke7lCJGahbOhdCuhV.jpg,0,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [16]:
#Pasar a csv el dataframe nuevo
dataframe.to_csv('movies_preprocesado.csv', index=False)